apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian
  namespace: guardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardian
  template:
    metadata:
      labels:
        app: guardian
    spec:
      containers:
        - name: guardian
          image: wooharbor.site/pocket-money-guardian/backend:0.0.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      imagePullSecrets:
        - name: woo-harbor
      volumes:
        - name: config-volume
          configMap:
            name: guardian-config
---
apiVersion: v1
kind: Service
metadata:
  name: guardian-service
  namespace: guardian
spec:
  selector:
    app: guardian
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31477
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guardian-config
  namespace: guardian
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:oracle:thin:@maewakka123.iptime.org:31521/WOORA
        username: GUARDIAN
        password: qhdks123#@#
        driver-class-name: oracle.jdbc.OracleDriver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.OracleDialect
      data:
        redis:
          host: maewakka123.iptime.org
          port: 31433
          password: qhdks123!#@
      mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: pocketmoneyguardian@gmail.com
        password: goma ccrr mlbs ifgb
        properties:
          mail:
            smtp:
              starttls:
                enable: true
                required: true
            auth: true
            debug: false
            mime:
              charset: UTF-8
        transport:
          protocol: smtp
    
    jwt:
      header: Authorization
      accessTime: 36000000000
      prefix: Bearer
      secretKey: cGVhY2gtcGlja2VyLXNwcmluZy1ib290LWp3dC1zZWNyZXQtd29vLXRlY2gtc3ByaW5nLWJvb3Qtand0LXRva2VuLXNlY3JldC1zcHJpbmctYm9vdC1qd3QtdG9rZW4tc2VjcmV0
    
    minio:
      endpoint: https://woominio.site
      access-token: EwYzdSQ2tlLhwvKyJ9ae
      secret-token: uZRsST5jJeTwJOH12BpHqcIrDZX5KgwkvCoLB5KG
      bucket-name: guardian